require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colors"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comments"
require "user.gitsigns"
require "user.nvim-tree"
require "nvim-tree".setup {}
require "user.bufferlines"
require "user.toggleterm"
